# Generated by Django 5.0.1 on 2026-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='illness',
            field=models.CharField(max_length=100),
        ),
    ]
